### ISSUE TITLE
no matching function for call

### ISSUE THREAD

**Issue by olijoe** [xunker/tvpkk#1]
I'm getting the error message:
error: no matching function for call to 'Trinket_Hid_Combo::mouseMove(int, int, uint8_t&, int)'

I have included your updated TrinketHidCombo.h and also tried the version from adafruit but nothing seems to help. 

I know this project is rather old but I hope you can help me :)

**Comment by olijoe** [comment]
I found the problem in line 128
    `TrinketHidCombo.mouseMove(0, 0, action.event_code, 0);`
has to be 
    `TrinketHidCombo.mouseMove(0, 0, action.event_code);`

now everything works fine for me.

**Comment by xunker** [comment]
Thank you for the report, and the solution! Unfortunately I wasn't able to duplicate this issue myself using the original TrinketHitCombo or my fork, but I hope that your information here will help anyone else who runs in to this problem.
